#-*- mode: ruby -*-
source 'https://rubygems.org'

gem 'rails', '4.1.2.rc1'

gem 'rails-api'

gem 'spring', :group => :development

gem 'sqlite3'

gem 'active_model_serializers'

gem 'parallel'

group :development do
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry'
  gem 'pry-rails'
end

gem 'nokogiri'

gem 'sparql-client', require: 'sparql/client'
gem 'rdf-turtle', require: 'rdf/turtle'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
